### ISSUE TITLE
errore com.android.systemiui su 5.3.6

### ISSUE THREAD

**Issue by Chazy12** [MishFdM/MIUI_V6_Italy#103]
È impossibile installare la 5.3.6 perché all'avvio si blocca subito il processo com.android.systemiui e va sempre in restart.
Da quello che ho potuto vedere, è un problema soltanto della ROM italiana e su mi3..

**Comment by ingbrzy** [comment]
can you post log message here..?

**Comment by Chazy12** [comment]
com.android.systemiui
Chazy
Il ingbrzy <notifications@github.com>, 09/mar/2015 20:09 ha scritto:can you post log message here..?

**Comment by ingbrzy** [comment]
please post full log message...

**Comment by Chazy12** [comment]
Can't post logcat log couse, after the reboot, the system is totally unpraticable. Always launcher restart, every 1 second. The error is com.android.systemiui..

**Comment by Chazy12** [comment]
As you can see, the problem is already know..
http://www.miui.it/forum/index.php?threads/dopo-aggiornamento-com-android-systemui-si-interrompe-allavvio.8208/
