### ISSUE TITLE
Play store graphic

### ISSUE THREAD

**Issue by foskikaiser** [MishFdM/MIUI_V6_Italy#99]
![cattura1](https://cloud.githubusercontent.com/assets/10382242/5633672/f0389ac8-95d9-11e4-902a-359ff8fcb314.PNG) noticed this graphical bug in loading download page in play store after rebooting phone or after closing and reopening play store

**Comment by ale8530** [comment]
This bug does not depend on translation.

We talked about it on the forum Miui Italy.
